export const SUPABASE_URL_ENV = "NEXT_PUBLIC_SUPABASE_URL";

export const SUPABASE_KEY_ENV_KEYS = [
  "SUPABASE_SECRET_KEY",
  "SUPABASE_SERVICE_ROLE_KEY",
  "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY",
  "NEXT_PUBLIC_SUPABASE_ANON_KEY",
] as const;

export const DEFAULT_STORAGE_BUCKET = "deco-spacio-images";

export const DECO_SPACIO_USER_ID_HEADER = "x-deco-spacio-user-id";
export const DECO_SPACIO_RECOVERY_KEY_HEADER = "x-deco-spacio-recovery-key";

export const DECO_SPACIO_USER_ID_HEADER_ENV = "SUPABASE_DECO_SPACIO_USER_ID";
export const DECO_SPACIO_RECOVERY_KEY_HEADER_ENV =
  "SUPABASE_DECO_SPACIO_RECOVERY_KEY";
